version: "3"

services:
  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server
    volumes:
      - redis:/data
  postgres:
    image: postgres:14.11-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=foc-fun-user
      - POSTGRES_DB=foc-fun-db
  backend:
    build:
      dockerfile: backend/Dockerfile
      context: .
    ports:
      - 8084:8084
    links:
      - redis
      - postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
  consumer:
    build:
      dockerfile: backend/Dockerfile.consumer
      context: .
    ports:
      - 8085:8085
    links:
      - redis
      - postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
  devnet:
    image: shardlabs/starknet-devnet-rs:0.2.2
    command:
      - --dump-on=block
      - --dump-path=/data/dump
      - --seed=42
    volumes:
      - devnet:/data
    ports:
      - 5050:5050
  updater:
    build:
      dockerfile: onchain/Dockerfile.update
      context: .
    depends_on:
      devnet:
        condition: service_started
    command: bash -c "./update_devnet.sh"
    volumes:
      - configs:/configs
  apibara:
    image: quay.io/apibara/starknet:1.5.0
    command:
      - start
      - --rpc=http://devnet:5050/rpc
      - --name=devnet
      - --head-refresh-interval-ms=1000
      - --wait-for-rpc
      - --address=0.0.0.0:7171
    environment:
      - XDG_DATA_HOME=/data
    volumes:
      - apibara:/data
    ports:
      - 7171:7171
    links:
      - backend
      - devnet
    depends_on:
      devnet:
        condition: service_started
  indexer:
    build:
      dockerfile: indexer/Dockerfile
      context: .
    depends_on:
      apibara:
        condition: service_started
    links:
      - backend
      - apibara
    environment:
      - APIBARA_STREAM_URL=http://foc-fun-apibara-1:7171
      - CONSUMER_TARGET_URL=http://foc-fun-consumer-1:8085/consume-indexer-msg
      - PERSIST_TO_REDIS=redis://foc-fun-redis-1:6379
      - INDEXER_ID=foc-fun-indexer-id
    volumes:
      - configs:/configs
    restart: on-failure
  frontend:
    build:
      dockerfile: frontend/Dockerfile
      context: .
    ports:
      - 3000:3000
    links:
      - backend
      - devnet
    volumes:
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/public/:/app/public
      - ./frontend/src:/app/src
      - configs:/app/src/configs

volumes:
  redis:
  postgres:
  devnet:
  apibara:
  configs:
